require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LtiAppsController do

  # This should return the minimal set of attributes required to create a valid
  # LtiApp. As you add validations to LtiApp, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LtiAppsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all lti_apps as @lti_apps" do
      lti_app = LtiApp.create! valid_attributes
      get :index, {}, valid_session
      assigns(:lti_apps).should eq([lti_app])
    end
  end

  describe "GET show" do
    it "assigns the requested lti_app as @lti_app" do
      lti_app = LtiApp.create! valid_attributes
      get :show, {:id => lti_app.to_param}, valid_session
      assigns(:lti_app).should eq(lti_app)
    end
  end

  describe "GET new" do
    it "assigns a new lti_app as @lti_app" do
      get :new, {}, valid_session
      assigns(:lti_app).should be_a_new(LtiApp)
    end
  end

  describe "GET edit" do
    it "assigns the requested lti_app as @lti_app" do
      lti_app = LtiApp.create! valid_attributes
      get :edit, {:id => lti_app.to_param}, valid_session
      assigns(:lti_app).should eq(lti_app)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LtiApp" do
        expect {
          post :create, {:lti_app => valid_attributes}, valid_session
        }.to change(LtiApp, :count).by(1)
      end

      it "assigns a newly created lti_app as @lti_app" do
        post :create, {:lti_app => valid_attributes}, valid_session
        assigns(:lti_app).should be_a(LtiApp)
        assigns(:lti_app).should be_persisted
      end

      it "redirects to the created lti_app" do
        post :create, {:lti_app => valid_attributes}, valid_session
        response.should redirect_to(LtiApp.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lti_app as @lti_app" do
        # Trigger the behavior that occurs when invalid params are submitted
        LtiApp.any_instance.stub(:save).and_return(false)
        post :create, {:lti_app => { "user" => "invalid value" }}, valid_session
        assigns(:lti_app).should be_a_new(LtiApp)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LtiApp.any_instance.stub(:save).and_return(false)
        post :create, {:lti_app => { "user" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lti_app" do
        lti_app = LtiApp.create! valid_attributes
        # Assuming there are no other lti_apps in the database, this
        # specifies that the LtiApp created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LtiApp.any_instance.should_receive(:update).with({ "user" => "" })
        put :update, {:id => lti_app.to_param, :lti_app => { "user" => "" }}, valid_session
      end

      it "assigns the requested lti_app as @lti_app" do
        lti_app = LtiApp.create! valid_attributes
        put :update, {:id => lti_app.to_param, :lti_app => valid_attributes}, valid_session
        assigns(:lti_app).should eq(lti_app)
      end

      it "redirects to the lti_app" do
        lti_app = LtiApp.create! valid_attributes
        put :update, {:id => lti_app.to_param, :lti_app => valid_attributes}, valid_session
        response.should redirect_to(lti_app)
      end
    end

    describe "with invalid params" do
      it "assigns the lti_app as @lti_app" do
        lti_app = LtiApp.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LtiApp.any_instance.stub(:save).and_return(false)
        put :update, {:id => lti_app.to_param, :lti_app => { "user" => "invalid value" }}, valid_session
        assigns(:lti_app).should eq(lti_app)
      end

      it "re-renders the 'edit' template" do
        lti_app = LtiApp.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LtiApp.any_instance.stub(:save).and_return(false)
        put :update, {:id => lti_app.to_param, :lti_app => { "user" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lti_app" do
      lti_app = LtiApp.create! valid_attributes
      expect {
        delete :destroy, {:id => lti_app.to_param}, valid_session
      }.to change(LtiApp, :count).by(-1)
    end

    it "redirects to the lti_apps list" do
      lti_app = LtiApp.create! valid_attributes
      delete :destroy, {:id => lti_app.to_param}, valid_session
      response.should redirect_to(lti_apps_url)
    end
  end

end
